#version: '3.9'
#services:
#  web-app:
#    build: .
#    ports:
#      - "5173:5173"  
#    volumes: 
#      - .:/app
#      - /app/node_modules
#    environment:
#      - CHOKIDAR_USEPOLLING=true


version: '3.9'
services:
  web-app:
    build: .
    ports:
      - "80:80"  # Cambiado a 80 para producción